# Generated by Django 4.1 on 2023-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("director", models.CharField(max_length=50)),
                ("rating", models.FloatField()),
                ("release_date", models.DateField()),
                ("length_in_minutes", models.IntegerField()),
            ],
        ),
    ]
