# Generated by Django 4.1.7 on 2023-03-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alternative_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("birthplace", models.CharField(max_length=100)),
                ("height_in_cm", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alternative_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("birthplace", models.CharField(max_length=100)),
                ("height_in_cm", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActorMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_time_in_minutes", models.IntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movieswebapp.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movieswebapp.movie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                through="movieswebapp.ActorMovie", to="movieswebapp.actor"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movieswebapp.director"
            ),
        ),
    ]
