# Generated by Django 4.1.7 on 2023-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0004_alter_actormovie_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="alternative_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="director",
            name="alternative_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
