name: sdi 
channels:
  - conda-forge
dependencies:
  - python >= 3.8
  - pip
  - django
  - djangorestframework
  - django-cors-headers
  - django-stubs
  - djangorestframework-stubs
  - drf-spectacular
  - pre-commit
  - pytest
  - pytest-django
