ALTER TABLE public."movieswebapp_userprofile" ADD CONSTRAINT "movieswebapp_userprofile_username_id_cd77db92_uniq" UNIQUE (user_id);
ALTER TABLE public."movieswebapp_actormovie" ADD CONSTRAINT "movieswebapp_actormovie_actor_id_movie_id_cf9f1b7e_uniq" UNIQUE (actor_id, movie_id);
ALTER TABLE public."django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE (app_label, model);
ALTER TABLE public."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE (user_id, permission_id);
ALTER TABLE public."auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE (user_id, group_id);
ALTER TABLE public."auth_user" ADD CONSTRAINT "auth_user_username_key" UNIQUE (username);
ALTER TABLE public."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE (content_type_id, codename);
ALTER TABLE public."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE (group_id, permission_id);
ALTER TABLE public."auth_group" ADD CONSTRAINT "auth_group_name_key" UNIQUE (name);
ALTER TABLE pg_catalog."pg_user_mapping" ADD CONSTRAINT "pg_user_mapping_user_server_index" UNIQUE (umuser, umserver);
ALTER TABLE pg_catalog."pg_type" ADD CONSTRAINT "pg_type_typname_nsp_index" UNIQUE (typname, typnamespace);
ALTER TABLE pg_catalog."pg_ts_template" ADD CONSTRAINT "pg_ts_template_tmplname_index" UNIQUE (tmplname, tmplnamespace);
ALTER TABLE pg_catalog."pg_ts_parser" ADD CONSTRAINT "pg_ts_parser_prsname_index" UNIQUE (prsname, prsnamespace);
ALTER TABLE pg_catalog."pg_ts_dict" ADD CONSTRAINT "pg_ts_dict_dictname_index" UNIQUE (dictname, dictnamespace);
ALTER TABLE pg_catalog."pg_ts_config" ADD CONSTRAINT "pg_ts_config_cfgname_index" UNIQUE (cfgname, cfgnamespace);
ALTER TABLE pg_catalog."pg_trigger" ADD CONSTRAINT "pg_trigger_tgrelid_tgname_index" UNIQUE (tgrelid, tgname);
ALTER TABLE pg_catalog."pg_transform" ADD CONSTRAINT "pg_transform_type_lang_index" UNIQUE (trftype, trflang);
ALTER TABLE pg_catalog."pg_tablespace" ADD CONSTRAINT "pg_tablespace_spcname_index" UNIQUE (spcname);
ALTER TABLE pg_catalog."pg_subscription" ADD CONSTRAINT "pg_subscription_subname_index" UNIQUE (subdbid, subname);
ALTER TABLE pg_catalog."pg_statistic_ext" ADD CONSTRAINT "pg_statistic_ext_name_index" UNIQUE (stxname, stxnamespace);
ALTER TABLE pg_catalog."pg_rewrite" ADD CONSTRAINT "pg_rewrite_rel_rulename_index" UNIQUE (ev_class, rulename);
ALTER TABLE pg_catalog."pg_replication_origin" ADD CONSTRAINT "pg_replication_origin_roname_index" UNIQUE (roname);
ALTER TABLE pg_catalog."pg_range" ADD CONSTRAINT "pg_range_rngmultitypid_index" UNIQUE (rngmultitypid);
ALTER TABLE pg_catalog."pg_publication_rel" ADD CONSTRAINT "pg_publication_rel_prrelid_prpubid_index" UNIQUE (prrelid, prpubid);
ALTER TABLE pg_catalog."pg_publication" ADD CONSTRAINT "pg_publication_pubname_index" UNIQUE (pubname);
ALTER TABLE pg_catalog."pg_proc" ADD CONSTRAINT "pg_proc_proname_args_nsp_index" UNIQUE (proname, proargtypes, pronamespace);
ALTER TABLE pg_catalog."pg_policy" ADD CONSTRAINT "pg_policy_polrelid_polname_index" UNIQUE (polrelid, polname);
ALTER TABLE pg_catalog."pg_opfamily" ADD CONSTRAINT "pg_opfamily_am_name_nsp_index" UNIQUE (opfmethod, opfname, opfnamespace);
ALTER TABLE pg_catalog."pg_operator" ADD CONSTRAINT "pg_operator_oprname_l_r_n_index" UNIQUE (oprname, oprleft, oprright, oprnamespace);
ALTER TABLE pg_catalog."pg_opclass" ADD CONSTRAINT "pg_opclass_am_name_nsp_index" UNIQUE (opcmethod, opcname, opcnamespace);
ALTER TABLE pg_catalog."pg_namespace" ADD CONSTRAINT "pg_namespace_nspname_index" UNIQUE (nspname);
ALTER TABLE pg_catalog."pg_language" ADD CONSTRAINT "pg_language_name_index" UNIQUE (lanname);
ALTER TABLE pg_catalog."pg_foreign_server" ADD CONSTRAINT "pg_foreign_server_name_index" UNIQUE (srvname);
ALTER TABLE pg_catalog."pg_foreign_data_wrapper" ADD CONSTRAINT "pg_foreign_data_wrapper_name_index" UNIQUE (fdwname);
ALTER TABLE pg_catalog."pg_extension" ADD CONSTRAINT "pg_extension_name_index" UNIQUE (extname);
ALTER TABLE pg_catalog."pg_event_trigger" ADD CONSTRAINT "pg_event_trigger_evtname_index" UNIQUE (evtname);
ALTER TABLE pg_catalog."pg_enum" ADD CONSTRAINT "pg_enum_typid_sortorder_index" UNIQUE (enumtypid, enumsortorder);
ALTER TABLE pg_catalog."pg_enum" ADD CONSTRAINT "pg_enum_typid_label_index" UNIQUE (enumtypid, enumlabel);
ALTER TABLE pg_catalog."pg_default_acl" ADD CONSTRAINT "pg_default_acl_role_nsp_obj_index" UNIQUE (defaclrole, defaclnamespace, defaclobjtype);
ALTER TABLE pg_catalog."pg_database" ADD CONSTRAINT "pg_database_datname_index" UNIQUE (datname);
ALTER TABLE pg_catalog."pg_conversion" ADD CONSTRAINT "pg_conversion_name_nsp_index" UNIQUE (conname, connamespace);
ALTER TABLE pg_catalog."pg_conversion" ADD CONSTRAINT "pg_conversion_default_index" UNIQUE (connamespace, conforencoding, contoencoding, oid);
ALTER TABLE pg_catalog."pg_constraint" ADD CONSTRAINT "pg_constraint_conrelid_contypid_conname_index" UNIQUE (conrelid, contypid, conname);
ALTER TABLE pg_catalog."pg_collation" ADD CONSTRAINT "pg_collation_name_enc_nsp_index" UNIQUE (collname, collencoding, collnamespace);
ALTER TABLE pg_catalog."pg_class" ADD CONSTRAINT "pg_class_relname_nsp_index" UNIQUE (relname, relnamespace);
ALTER TABLE pg_catalog."pg_cast" ADD CONSTRAINT "pg_cast_source_target_index" UNIQUE (castsource, casttarget);
ALTER TABLE pg_catalog."pg_authid" ADD CONSTRAINT "pg_authid_rolname_index" UNIQUE (rolname);
ALTER TABLE pg_catalog."pg_auth_members" ADD CONSTRAINT "pg_auth_members_member_role_index" UNIQUE (member, roleid);
ALTER TABLE pg_catalog."pg_attribute" ADD CONSTRAINT "pg_attribute_relid_attnam_index" UNIQUE (attrelid, attname);
ALTER TABLE pg_catalog."pg_attrdef" ADD CONSTRAINT "pg_attrdef_adrelid_adnum_index" UNIQUE (adrelid, adnum);
ALTER TABLE pg_catalog."pg_amproc" ADD CONSTRAINT "pg_amproc_fam_proc_index" UNIQUE (amprocfamily, amproclefttype, amprocrighttype, amprocnum);
ALTER TABLE pg_catalog."pg_amop" ADD CONSTRAINT "pg_amop_opr_fam_index" UNIQUE (amopopr, amoppurpose, amopfamily);
ALTER TABLE pg_catalog."pg_amop" ADD CONSTRAINT "pg_amop_fam_strat_index" UNIQUE (amopfamily, amoplefttype, amoprighttype, amopstrategy);
ALTER TABLE pg_catalog."pg_am" ADD CONSTRAINT "pg_am_name_index" UNIQUE (amname);
ALTER TABLE public."movieswebapp_userprofile" ADD CONSTRAINT "movieswebapp_userprofile_pkey" PRIMARY KEY (id);
ALTER TABLE public."movieswebapp_movie" ADD CONSTRAINT "movieswebapp_movie_pkey" PRIMARY KEY (id);
ALTER TABLE public."movieswebapp_director" ADD CONSTRAINT "movieswebapp_director_pkey" PRIMARY KEY (id);
ALTER TABLE public."movieswebapp_actormovie" ADD CONSTRAINT "movieswebapp_actormovie_pkey" PRIMARY KEY (id);
ALTER TABLE public."movieswebapp_actor" ADD CONSTRAINT "movieswebapp_actor_pkey" PRIMARY KEY (id);
ALTER TABLE public."django_session" ADD CONSTRAINT "django_session_pkey" PRIMARY KEY (session_key);
ALTER TABLE public."django_migrations" ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY (id);
ALTER TABLE public."django_content_type" ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY (id);
ALTER TABLE public."django_admin_log" ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY (id);
ALTER TABLE public."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_pkey" PRIMARY KEY (id);
ALTER TABLE public."auth_user_groups" ADD CONSTRAINT "auth_user_groups_pkey" PRIMARY KEY (id);
ALTER TABLE public."auth_user" ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY (id);
ALTER TABLE public."auth_permission" ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY (id);
ALTER TABLE public."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY (id);
ALTER TABLE public."auth_group" ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY (id);
ALTER TABLE pg_catalog."pg_user_mapping" ADD CONSTRAINT "pg_user_mapping_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_type" ADD CONSTRAINT "pg_type_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_ts_template" ADD CONSTRAINT "pg_ts_template_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_ts_parser" ADD CONSTRAINT "pg_ts_parser_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_ts_dict" ADD CONSTRAINT "pg_ts_dict_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_ts_config_map" ADD CONSTRAINT "pg_ts_config_map_index" PRIMARY KEY (mapcfg, maptokentype, mapseqno);
ALTER TABLE pg_catalog."pg_ts_config" ADD CONSTRAINT "pg_ts_config_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_trigger" ADD CONSTRAINT "pg_trigger_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_transform" ADD CONSTRAINT "pg_transform_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_tablespace" ADD CONSTRAINT "pg_tablespace_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_subscription_rel" ADD CONSTRAINT "pg_subscription_rel_srrelid_srsubid_index" PRIMARY KEY (srrelid, srsubid);
ALTER TABLE pg_catalog."pg_subscription" ADD CONSTRAINT "pg_subscription_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_statistic_ext_data" ADD CONSTRAINT "pg_statistic_ext_data_stxoid_index" PRIMARY KEY (stxoid);
ALTER TABLE pg_catalog."pg_statistic_ext" ADD CONSTRAINT "pg_statistic_ext_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_statistic" ADD CONSTRAINT "pg_statistic_relid_att_inh_index" PRIMARY KEY (starelid, staattnum, stainherit);
ALTER TABLE pg_catalog."pg_shseclabel" ADD CONSTRAINT "pg_shseclabel_object_index" PRIMARY KEY (objoid, classoid, provider);
ALTER TABLE pg_catalog."pg_shdescription" ADD CONSTRAINT "pg_shdescription_o_c_index" PRIMARY KEY (objoid, classoid);
ALTER TABLE pg_catalog."pg_sequence" ADD CONSTRAINT "pg_sequence_seqrelid_index" PRIMARY KEY (seqrelid);
ALTER TABLE pg_catalog."pg_seclabel" ADD CONSTRAINT "pg_seclabel_object_index" PRIMARY KEY (objoid, classoid, objsubid, provider);
ALTER TABLE pg_catalog."pg_rewrite" ADD CONSTRAINT "pg_rewrite_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_replication_origin" ADD CONSTRAINT "pg_replication_origin_roiident_index" PRIMARY KEY (roident);
ALTER TABLE pg_catalog."pg_range" ADD CONSTRAINT "pg_range_rngtypid_index" PRIMARY KEY (rngtypid);
ALTER TABLE pg_catalog."pg_publication_rel" ADD CONSTRAINT "pg_publication_rel_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_publication" ADD CONSTRAINT "pg_publication_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_proc" ADD CONSTRAINT "pg_proc_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_policy" ADD CONSTRAINT "pg_policy_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_partitioned_table" ADD CONSTRAINT "pg_partitioned_table_partrelid_index" PRIMARY KEY (partrelid);
ALTER TABLE pg_catalog."pg_opfamily" ADD CONSTRAINT "pg_opfamily_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_operator" ADD CONSTRAINT "pg_operator_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_opclass" ADD CONSTRAINT "pg_opclass_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_namespace" ADD CONSTRAINT "pg_namespace_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_largeobject_metadata" ADD CONSTRAINT "pg_largeobject_metadata_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_largeobject" ADD CONSTRAINT "pg_largeobject_loid_pn_index" PRIMARY KEY (loid, pageno);
ALTER TABLE pg_catalog."pg_language" ADD CONSTRAINT "pg_language_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_init_privs" ADD CONSTRAINT "pg_init_privs_o_c_o_index" PRIMARY KEY (objoid, classoid, objsubid);
ALTER TABLE pg_catalog."pg_inherits" ADD CONSTRAINT "pg_inherits_relid_seqno_index" PRIMARY KEY (inhrelid, inhseqno);
ALTER TABLE pg_catalog."pg_index" ADD CONSTRAINT "pg_index_indexrelid_index" PRIMARY KEY (indexrelid);
ALTER TABLE pg_catalog."pg_foreign_table" ADD CONSTRAINT "pg_foreign_table_relid_index" PRIMARY KEY (ftrelid);
ALTER TABLE pg_catalog."pg_foreign_server" ADD CONSTRAINT "pg_foreign_server_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_foreign_data_wrapper" ADD CONSTRAINT "pg_foreign_data_wrapper_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_extension" ADD CONSTRAINT "pg_extension_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_event_trigger" ADD CONSTRAINT "pg_event_trigger_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_enum" ADD CONSTRAINT "pg_enum_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_description" ADD CONSTRAINT "pg_description_o_c_o_index" PRIMARY KEY (objoid, classoid, objsubid);
ALTER TABLE pg_catalog."pg_default_acl" ADD CONSTRAINT "pg_default_acl_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_db_role_setting" ADD CONSTRAINT "pg_db_role_setting_databaseid_rol_index" PRIMARY KEY (setdatabase, setrole);
ALTER TABLE pg_catalog."pg_database" ADD CONSTRAINT "pg_database_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_conversion" ADD CONSTRAINT "pg_conversion_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_constraint" ADD CONSTRAINT "pg_constraint_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_collation" ADD CONSTRAINT "pg_collation_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_class" ADD CONSTRAINT "pg_class_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_cast" ADD CONSTRAINT "pg_cast_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_authid" ADD CONSTRAINT "pg_authid_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_auth_members" ADD CONSTRAINT "pg_auth_members_role_member_index" PRIMARY KEY (roleid, member);
ALTER TABLE pg_catalog."pg_attribute" ADD CONSTRAINT "pg_attribute_relid_attnum_index" PRIMARY KEY (attrelid, attnum);
ALTER TABLE pg_catalog."pg_attrdef" ADD CONSTRAINT "pg_attrdef_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_amproc" ADD CONSTRAINT "pg_amproc_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_amop" ADD CONSTRAINT "pg_amop_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_am" ADD CONSTRAINT "pg_am_oid_index" PRIMARY KEY (oid);
ALTER TABLE pg_catalog."pg_aggregate" ADD CONSTRAINT "pg_aggregate_fnoid_index" PRIMARY KEY (aggfnoid);
ALTER TABLE public."django_admin_log" ADD CONSTRAINT "django_admin_log_action_flag_check" CHECK ((action_flag >= 0));
ALTER TABLE public."movieswebapp_userprofile" ADD CONSTRAINT "movieswebapp_userprofile_user_id_df92a5ca_fk_auth_user_username" FOREIGN KEY (user_id) REFERENCES auth_user(username) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_movie" ADD CONSTRAINT "movieswebapp_movie_director_id_a5a67a46_fk_moviesweb" FOREIGN KEY (director_id) REFERENCES movieswebapp_director(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_movie" ADD CONSTRAINT "movieswebapp_movie_added_by_id_c00a1ef8_fk_auth_user_id" FOREIGN KEY (added_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_director" ADD CONSTRAINT "movieswebapp_director_added_by_id_5f8503dd_fk_auth_user_id" FOREIGN KEY (added_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_actormovie" ADD CONSTRAINT "movieswebapp_actormovie_added_by_id_32e6115c_fk_auth_user_id" FOREIGN KEY (added_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_actormovie" ADD CONSTRAINT "movieswebapp_actormo_movie_id_10f0879f_fk_moviesweb" FOREIGN KEY (movie_id) REFERENCES movieswebapp_movie(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_actormovie" ADD CONSTRAINT "movieswebapp_actormo_actor_id_9add9887_fk_moviesweb" FOREIGN KEY (actor_id) REFERENCES movieswebapp_actor(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."movieswebapp_actor" ADD CONSTRAINT "movieswebapp_actor_added_by_id_47979bb8_fk_auth_user_id" FOREIGN KEY (added_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public."auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;
