# Generated by Django 4.1.7 on 2023-03-21 18:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0003_actormovie_salary_in_usd"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="actormovie",
            unique_together={("actor", "movie")},
        ),
    ]
