# Generated by Django 4.2 on 2023-04-18 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0007_alter_actor_options_alter_actormovie_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="actormovie",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["name"]},
        ),
    ]
