# Generated by Django 4.2 on 2023-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0008_alter_actor_options_alter_actormovie_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(
                fields=["name", "id"], name="movieswebap_name_7633f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actormovie",
            index=models.Index(fields=["id"], name="movieswebap_id_1e5bda_idx"),
        ),
        migrations.AddIndex(
            model_name="director",
            index=models.Index(
                fields=["name", "id"], name="movieswebap_name_92b065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["name", "id"], name="movieswebap_name_879852_idx"
            ),
        ),
    ]
