# Generated by Django 4.2 on 2023-04-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0009_alter_actor_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="actor",
            name="movieswebap_name_7633f0_idx",
        ),
        migrations.AddIndex(
            model_name="actor",
            index=models.Index(
                fields=["date_of_birth"], name="movieswebap_date_of_fbcb14_idx"
            ),
        ),
    ]
