# Generated by Django 4.2 on 2023-04-29 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0011_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="validation_code",
            new_name="activation_code",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="validation_expiry_date",
            new_name="activation_expiry_date",
        ),
    ]
