# Generated by Django 4.2 on 2023-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "movieswebapp",
            "0013_actor_added_by_actormovie_added_by_director_added_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default="username", max_length=150),
            preserve_default=False,
        ),
    ]
