# Generated by Django 4.2 on 2023-05-01 14:10

from django.db import migrations


def set_usernames(apps, schema_editor):
    UserProfile = apps.get_model("movieswebapp", "UserProfile")
    for profile in UserProfile.objects.all():
        profile.username = profile.user.username
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0014_userprofile_username"),
    ]

    operations = [
        migrations.RunPython(set_usernames),
    ]
