# Generated by Django 4.2 on 2023-05-01 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0016_alter_userprofile_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
