# Generated by Django 4.2 on 2023-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieswebapp", "0017_remove_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="username",
            new_name="user",
        ),
    ]
